spring:
  application:
    name: question-service
  datasource:
    url: jdbc:mysql://localhost:3306/question_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
server:
  port: ${SERVER_PORT}
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/, http://localhost:8762/eureka/
